version: '3.8'
services:
  # PHP Service
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./project:/var/www
    extra_hosts:
        - host.docker.internal:host-gateway
    networks:
      symfony:

  # Nginx Service
  nginx:
    container_name: nginx
    build:
        context: ./docker/nginx
        dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./project:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      symfony:
    depends_on:
      - php

  # PostgreSQL Service
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    volumes:
      - dbData:/var/lib/postgresql/data
    networks:
      symfony:


networks:
  symfony:

volumes:
  dbData:


